version: "3"
services:
  gym-app:
    image: gym-app:v1.0
    container_name: gym-app
    hostname: gym-app
    ports:
      - "8080:8080"

  mysql-db:
     image: mysql:8.0
     container_name: mysql
     hostname: mysql
     environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_DATABASE: "weather_db"
       MYSQL_USER: "user"
       MYSQL_PASSWORD: "password"
     ports:
       - "3307:3306"
     volumes:
       - ./data/mysql/:/var/lib/mysql